### ISSUE TITLE
Failed to find match for field 'distance' when playing rosbag file

### ISSUE THREAD

**Issue by akamob** [AIS-Bonn/object_detection_in_laser_range_data#1]
Hi,

When I use my rosbag file, the terminal has the following warning:
![Screenshot from 2021-09-16 22-42-02](https://user-images.githubusercontent.com/49118957/133633234-0654e067-5751-4e22-a489-be4237e9bcac.png)

In rviz, I change the Fixed Frame to velodyne, and I can see the "Input Point Cloud", but "Segmented Cloud" doesn't appear anything.
![Screenshot from 2021-09-16 22-49-51](https://user-images.githubusercontent.com/49118957/133634927-95e34fd3-5474-4e5d-86d5-306bc95d1089.png)

This is my rosbag file info:
![Screenshot from 2021-09-16 22-56-53](https://user-images.githubusercontent.com/49118957/133635509-8ae53936-3ffe-4a9b-96ae-18e2c439a2c4.png)

Did I miss something in my setup?
Any help is much appreciated!

**Comment by Razlaw** [comment]
Yes, you missed something ;) 
In the readme in the section [Limitations](https://github.com/AIS-Bonn/object_detection_in_laser_range_data#limitations) it says "The input point cloud has to consist of points providing a field named distance.".

You can either write a node that takes your point clouds and computes the distance field from the point coordinate and the position of the sensor or adapt the velodyne driver to output points with that field, because the driver already works with the distance measurement to compute the xyz coordinate. 

If you want the full functionality the velodyne driver needs to output organized point clouds. 
Meaning, it should NOT delete invalid measurements but keep them with nan values. 
This way you keep the grid structure of the measurements with exactly the same number of measurements in each scan line. 

This type of point cloud is provided in the data set linked in the readme.
